[package]
name = "monotron-app"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]

[lib]
crate-type = ["staticlib", "rlib"]

[features]
print-panic = []

[target.'cfg(not(target_os = "none"))'.dependencies]
sdl2 = "0.32"
vga-framebuffer = "0.7.5"
lazy_static = "1.3"
