[package]
name = "monotron-app"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]

[profile.release]
lto = true
debug = true
codegen-units = 1
opt-level = "z"

[features]
print-panic = []

[dependencies]
