[package]
name = "monotron-app"
version = "0.5.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
readme = "README.md"
licence = "LICENCE.md"
description = "Support crate for writing Monotron applications."
keywords = ["sdl2", "monotron", "embedded", "arm"]

[lib]
crate-type = ["staticlib", "rlib"]

[features]
print-panic = []

[target.'cfg(not(target_os = "none"))'.dependencies]
sdl2 = "0.32"
vga-framebuffer = "0.7.5"
lazy_static = "1.3"
