[package]
name = "monotron-app"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]

[features]
print-panic = []

[target.'cfg(not(target_os = "none"))'.dependencies]
ncurses = "5.99.0"
