[package]
name = "monotron-app"
version = "0.1.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]

[features]
print-panic = []

[target.'cfg(not(target_os = "none"))'.dependencies]
ncurses = { version = "5.99.0", features = ["wide"] }
libc = { version = "0.2", default-features = false }
